spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/rfid
    username: rfid
    password: rfid

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true